In [101]:
import numpy as np

In [102]:
x = np.linspace(1, 50, 50)

In [103]:
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [104]:
sigma = 0.3          # volatility
r = 0.25             # interest rate 
K = 10              # strike price
X = 50               # asset value
T = 1               # time
M = 3
N = 10

In [105]:
dx = X / M  #  Space steps
dt = T / N      #  Time steps
#x = (1:M)'*dx;
x = np.linspace(1, M, M) * dx
 

In [106]:
x-K

array([ 6.66666667, 23.33333333, 40.        ])

In [107]:
a = -(sigma**2 * np.linspace(1, M, M)**2 - r * np.linspace(1, M, M)) / 2
b = sigma**2 * np.linspace(1, M, M)**2 + r
c = -(sigma**2 * np.linspace(1, M, M)**2 + r * np.linspace(1, M, M)) / 2
a[-1] = a[-1] + c[-1]

In [108]:
a = a/2;
c = c/2;
b1 = 1/dt + b/2;
b2 = 1/dt - b/2;

#a1 = [a[(2:M)];  0];
a1 = np.hstack((a[1:-1], np.zeros(1)))
#c1 = [np.zeros(1);  c(1:M-1)]
c1 = np.hstack((np.zeros(1), c[0:-2]))

In [109]:
np.size(c1)

2

In [110]:

#C = spdiags([a1  b1  c1],-1:1,M,M)
C = np.diag(c1,1) + np.diag(a1,-1) + np.diag(b1)
#B = spdiags([-a1  b2  -c1],-1:1,M,M)
B = np.diag(-c1,1) + np.diag(-a1,-1) + np.diag(b1)

U = np.zeros((N, M))
g = np.maximum(x-K,np.zeros(M)) 
u = g.reshape(M,1)
f = np.zeros((M,1))

In [111]:
B @ u + f

array([[ 67.8       ],
       [243.61666667],
       [421.2       ]])

In [112]:
U[4]

array([0., 0., 0.])

In [113]:
f[M-1] = -2*dx*c[M-1]
#j = N:-1:1 
for j in range(N-1,0,-1):   
    rhs = B @ u + f
    # u = C \ rhs
    u = np.linalg.solve(C, rhs)
    U[j] = u.reshape(1,M)

In [114]:
U

array([[ 0.        ,  0.        ,  0.        ],
       [ 6.66666667, 29.68947113, 51.11111111],
       [ 6.66666667, 28.90176769, 49.87654321],
       [ 6.66666667, 28.13443073, 48.64197531],
       [ 6.66666667, 27.38746024, 47.40740741],
       [ 6.66666667, 26.66085623, 46.17283951],
       [ 6.66666667, 25.9546187 , 44.9382716 ],
       [ 6.66666667, 25.26874764, 43.7037037 ],
       [ 6.66666667, 24.60324306, 42.4691358 ],
       [ 6.66666667, 23.95810496, 41.2345679 ]])